version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
            - ./storage:/var/www/storage
            - ./php.ini:/usr/local/etc/php/php.ini
        ports:
            - 8000:8000
        networks:
            - app-network
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: guest_service
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
